# Generated by Django 4.2.30 on 2026-06-07 21:57

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('user', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('BTCUSDT', 'Bitcoin'), ('ETHUSDT', 'Ethereum'), ('BNBUSDT', 'BNB'), ('SOLUSDT', 'Solana'), ('XRPUSDT', 'XRP')], max_length=20)),
                ('type', models.CharField(choices=[('BUY', 'Achat'), ('SELL', 'Vente')], max_length=4)),
                ('quantite', models.DecimalField(decimal_places=8, max_digits=18)),
                ('prix_exec', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais', models.DecimalField(decimal_places=4, max_digits=10)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_id', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='users.virtualaccount')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.IntegerField(default=0)),
                ('valeur_totale', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('pnl_eur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pnl_pct', models.FloatField(default=0.0)),
                ('nb_trades', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='users.virtualaccount')),
            ],
            options={
                'ordering': ['rang'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('BTCUSDT', 'Bitcoin'), ('ETHUSDT', 'Ethereum'), ('BNBUSDT', 'BNB'), ('SOLUSDT', 'Solana'), ('XRPUSDT', 'XRP')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('prix_moyen', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('prix_actuel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.virtualaccount')),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('account', 'symbol')},
            },
        ),
    ]
